/**
 * Generated by tinybird migrate.
 * Review endpoint output schemas and any defaults before production use.
 */

import { createKafkaConnection, defineDatasource, definePipe, defineMaterializedView, defineCopyPipe, node, t, engine, p } from "@tinybirdco/sdk";

// Connections

export const stream = createKafkaConnection("stream", {
  bootstrapServers: "localhost:9092",
});

// Datasources

export const events = defineDatasource("events", {
  jsonPaths: false,
  schema: {
    event_id: t.string(),
    user_id: t.uint64(),
    created_at: t.dateTime(),
  },
  engine: engine.mergeTree({ sortingKey: "event_id" }),
  kafka: {
    connection: stream,
    topic: "events_topic",
  },
});

// Pipes

export const eventsEndpoint = definePipe("events_endpoint", {
  params: {
    user_id: p.uint64(),
  },
  nodes: [
    node({
      name: "source",
      sql: `
SELECT event_id, user_id
FROM events
      `,
    }),
    node({
      name: "endpoint",
      sql: `
SELECT event_id AS event_id, user_id AS user_id
FROM source
WHERE user_id = {{UInt64(user_id)}}
      `,
    }),
  ],
  endpoint: true,
  output: {
    event_id: t.string(),
    user_id: t.string(),
  },
  tokens: [
    { name: "endpoint_token" },
  ],
});
