// Auto-generated by @tinybird/sdk - DO NOT EDIT
// This file is regenerated on every build. Manual changes will be overwritten.

import { createTinybirdClient, type InferRow, type InferParams, type InferOutputRow } from "@tinybird/sdk";

import { dailyPageStats, events, pageViews } from "./tinybird/datasources";
import { dailyPageStatsMv, dailyStats, pageViewsOverTime, topEvents, topPages } from "./tinybird/pipes";

// Typed Tinybird client
export const tinybird = createTinybirdClient({
  datasources: { dailyPageStats, events, pageViews },
  pipes: { dailyPageStatsMv, dailyStats, pageViewsOverTime, topEvents, topPages },
});

// Re-export entities for convenience
export { dailyPageStats, events, pageViews } from "./tinybird/datasources";
export { dailyPageStatsMv, dailyStats, pageViewsOverTime, topEvents, topPages } from "./tinybird/pipes";

// Inferred types from entity definitions
export type DailyPageStatsRow = InferRow<typeof dailyPageStats>;
export type EventsRow = InferRow<typeof events>;
export type PageViewsRow = InferRow<typeof pageViews>;
export type DailyPageStatsMvParams = InferParams<typeof dailyPageStatsMv>;
export type DailyPageStatsMvOutput = InferOutputRow<typeof dailyPageStatsMv>;
export type DailyStatsParams = InferParams<typeof dailyStats>;
export type DailyStatsOutput = InferOutputRow<typeof dailyStats>;
export type PageViewsOverTimeParams = InferParams<typeof pageViewsOverTime>;
export type PageViewsOverTimeOutput = InferOutputRow<typeof pageViewsOverTime>;
export type TopEventsParams = InferParams<typeof topEvents>;
export type TopEventsOutput = InferOutputRow<typeof topEvents>;
export type TopPagesParams = InferParams<typeof topPages>;
export type TopPagesOutput = InferOutputRow<typeof topPages>;
